mybatis-plus:
  type-aliases-package: top.zhixingege.common.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: zhangzihao123
  redis:
    timeout: 600
