server:
  port: '@web.port@'

eureka:
  port: '@eureka.port@'
  ip: '@eureka.ip@'
  url-name: '@eureka.url.name@'
  instance:
    # 把本机IP注册到eureka而不是本机机器名
    preferIpAddress: true
    # 把本机IP注册到eureka，由下面参数组成
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@${eureka.ip}:${eureka.port}/${eureka.url-name}/

spring:
  application:
    name: '@web.application.name@'
  cloud:
    loadbalancer:
      retry:
        # 关闭重试
        enabled: false
    sentinel:
      transport:
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer。如果端口被占用会往后+1，直到没有占用
        port: '@sentinel.port@'
        dashboard: localhost:9910
  profiles:
    # 使用的配置文件后缀application-feign.yml
    active: feign,common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: zhangzihao123
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 600000
  cache:
    type: redis
    redis:
      cache-null-values: true
      use-key-prefix: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

my:
  gateway:
    ip: @eureka.ip@
    port: @gateway.port@