server:
  port: '@spider.port@'

eureka:
  port: '@eureka.port@'
  ip: '@eureka.ip@'
  url-name: '@eureka.url.name@'
  instance:
    # ???IP???eureka????????
    preferIpAddress: true
    # ???IP???eureka????????
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://@eureka.user.name@:@eureka.user.password@@${eureka.ip}:${eureka.port}/${eureka.url-name}/

spring:
  application:
    name: '@spider.application.name@'
  cloud:
    loadbalancer:
      retry:
        # ????
        enabled: false
  profiles:
    # 使用的配置文件后缀application-security.yml。一个或多个，中间英文逗号分开
    active: common
reflect:
  basePackage: "top.zhixingege.spider.component.factor.spiderExecutor."
mail:
  bccMail: "1431105872@qq.com"